logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: INFO
    org.springframework.jdbc.core.StatementCreatorUtils: INFO
    org.springframework.batch.core.step: INFO
    com.zaxxer.hikari: INFO

spring:
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/music?autoReconnect=true
    username: root
    password: 698427
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql

batch:
  resource:
    location: classpath:/musicDataset.json