spring:
  main:
    web-application-type: reactive
  r2dbc:
    url: r2dbc:mysql://localhost:3307/music?autoReconnect=true
    username: root
    password: 123456
    pool:
      initial-size: 5
      max-size: 20
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.r2dbc.pool: DEBUG

springdoc:
  swagger-ui:
    path: /music/swagger-ui.html
  api-docs:
    path: /music
  override-with-generic-response: false