spring:
  main:
    web-application-type: reactive
  r2dbc:
    url: r2dbc:mysql://localhost:3306/music?autoReconnect=true
    username: root
    password: 698427
    pool:
      initial-size: 5
      max-size: 20
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.r2dbc.pool: DEBUG
